/*
 * File:   test_student_t.c
 * Author: anthony
 *
 * Created on February 17, 2010, 7:03 AM
 */

#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

#include "student_t.h"

void usage() {
    fprintf(stderr, "USAGE: student_t_table <max_deg_freedom> <percentage_two_sided>\n");
}

/*
 *
 */
int main(int argc, char** argv) {

    if (argc < 3) {
        usage();
        exit(2);
    }

    int ndeg_freedom = atoi(argv[1]);
    double percentage = atof(argv[2]);

    fprintf(stdout, "/* Table auto-generated by command:   %s %s %s\n", argv[0], argv[1], argv[2]);
    fprintf(stdout, " * Table gives two-sided Student's t distribution for %.2f%% probability\n", percentage);
    percentage = 100.0 - 0.5 * (100.0 - percentage);
    fprintf(stdout, " * Table gives one-sided Student's t distribution for %.2f%% probability\n*/\n", percentage);
    fprintf(stdout, "#define STUDENT_T_NUM_DEG_FREEDOM_MAX %d\n", ndeg_freedom);
    fprintf(stdout, "static double student_t_value[STUDENT_T_NUM_DEG_FREEDOM_MAX] = {\n");

    // correct percentage to one-sided

    int nd;
    for (nd = 1; nd <= ndeg_freedom; nd++) {
        fprintf(stdout, "%f,\n", student_t_inv(nd, percentage / 100.0));
    }

    fprintf(stdout, "};\n");

    return (0);
}

